export const SWEDISH_REGIONS = [
  'Blekinge',
  'Dalarna',
  'Gotland',
  'Gävleborg',
  'Halland',
  'Jämtland',
  'Jönköping',
  'Kalmar',
  'Kronoberg',
  'Norrbotten',
  'Skåne',
  'Stockholm',
  'Södermanland',
  'Uppsala',
  'Värmland',
  'Västerbotten',
  'Västernorrland',
  'Västmanland',
  'Västra Götaland',
  'Örebro',
  'Östergötland',
] as const;

export type SwedishRegion = typeof SWEDISH_REGIONS[number];

export const REGION_DISPLAY_NAMES: Record<string, string> = {
  'Blekinge': 'Blekinge län',
  'Dalarna': 'Dalarnas län',
  'Gotland': 'Gotlands län',
  'Gävleborg': 'Gävleborgs län',
  'Halland': 'Hallands län',
  'Jämtland': 'Jämtlands län',
  'Jönköping': 'Jönköpings län',
  'Kalmar': 'Kalmar län',
  'Kronoberg': 'Kronobergs län',
  'Norrbotten': 'Norrbottens län',
  'Skåne': 'Skåne län',
  'Stockholm': 'Stockholms län',
  'Södermanland': 'Södermanlands län',
  'Uppsala': 'Uppsala län',
  'Värmland': 'Värmlands län',
  'Västerbotten': 'Västerbottens län',
  'Västernorrland': 'Västernorrlands län',
  'Västmanland': 'Västmanlands län',
  'Västra Götaland': 'Västra Götalands län',
  'Örebro': 'Örebro län',
  'Östergötland': 'Östergötlands län',
};
